"""Setup Array Handling and stodge for Artist and Venue Models

Revision ID: 05af13fe266e
Revises: a6cfac7df237
Create Date: 2022-09-02 10:51:56.382045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05af13fe266e'
down_revision = 'a6cfac7df237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.add_column('venue', sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###
