"""Genres update

Revision ID: 84c9284d335b
Revises: 874ed3fd46fc
Create Date: 2022-09-01 17:05:16.975076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c9284d335b'
down_revision = '874ed3fd46fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('venue', sa.Column('genres', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###
