"""Updated genre type to array on artist and venue model

Revision ID: 874ed3fd46fc
Revises: 94f1c8e42b0d
Create Date: 2022-09-01 14:02:03.862451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874ed3fd46fc'
down_revision = '94f1c8e42b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'genres')
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
