"""Removed extra fields on Show model after normalization

Revision ID: 94f1c8e42b0d
Revises: bc9b0c62e73f
Create Date: 2022-08-28 12:04:20.824618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f1c8e42b0d'
down_revision = 'bc9b0c62e73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'past_shows')
    op.drop_column('artist', 'past_shows_count')
    op.drop_column('artist', 'upcoming_shows_count')
    op.drop_column('artist', 'upcoming_shows')
    op.drop_column('show', 'venue_name')
    op.drop_column('show', 'artist_name')
    op.drop_column('show', 'artist_image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('artist_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('venue_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('past_shows', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
