"""Setup Array Handling and stodge for Artist and Venue Models

Revision ID: a6cfac7df237
Revises: 84c9284d335b
Create Date: 2022-09-02 10:51:25.542633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6cfac7df237'
down_revision = '84c9284d335b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'genres')
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('genres', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
